Improve srcflux documentation
cxcsds/ciao-contrib pull request #521
Opened 2021-11-01 18:22 UTC by hamogu

This PR has two changes in one. Due to the way I wrote it, they are in the same commit,
but I can separate them if needed.

- The upper end of a credible interval is not the same as the upper limit for a non-detection.
  Previously, this was implied by the text, so I've added an explicit paragraph on that.
  For more details see, e.g. [Kashayap et al. (2010)](https://iopscience.iop.org/article/10.1088/0004-637X/719/1/900)
- aprates is a fully Basian computation, so the term "confidence interval" is not appropriate.

I have not run this through ahelp yet to check that it renders correctly, because I want to achieve agreement that we actually want to do these changes first.

Note: My editor is set to automatically remove trailing which space, so some lines appear to be edited without reason. I can revert those if you need me to, but I'd rather not do it now if I don't have to.

Note: While this also relates to srcflux, #520 is separate in that it only changes a single line in the output on screen for more pleasing formatting, while this PR includes substantial changes to the content and meaning of the documentation.

2021-11-05 20:04 UTC, DougBurke commented
@hamogu - I split out the trailing-whitespace change to make the content change easier to read. It should be okay but the devil is in the rebase-details...

2021-11-05 20:05 UTC, DougBurke commented
@anetasie - can you review Moritz's changes in commit https://github.com/cxcsds/ciao-contrib/pull/521/commits/76d36b1c9f3eae9da2f27fa8e5c2164263a96161 based on our script discussions earlier this week?

2021-11-10 02:23 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	but should correctly be called credible interval.
I would not get into the discussion of the difference between the correct/incorrect names, so confidence or credible interval in the documentation. Suggest change lines 76-77 to:
"thus the result is a credible interval (confidence interval for the frequentist calculation), which is CONF parameter."

2021-11-10 02:57 UTC, anetasie requested changes
@hamogu Thank you for these updates. I left some comments to the text and suggested changes.

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +      </PARA>
Perhaps we should just quote the exact paragraph from Kashyap et al 2010 which has a very good description of the problem in Sec.2.1, or slightly shorter version, or just refer to this paragraph in the text. 

I would rephrase the current text and just state:
"The tool does not return upper limit and that the reported values are always calculated for lower and upper confidence bound. The upper limit calculation requires a detection threshold which does not dependent on the number of counts or the source flux. The detection threshold is not used in this tool. See Kashyap et al 2010, for full discussion of the difference between confidence bounds and upper limits."

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	    net counts are 0, then only the upper end of the range is reported.
we can say "upper bound of the interval" instead of "end of the range"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	    indicates that only the upper end of the credible interval is available.</DATA>
change to "the upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	  of NaN indicates that only the upper end of the credible interval is available as
"upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	  represent the upper end of the credible interval of the count rate.</DATA>
change to "upper bound of the credible interval for the count rate".

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	    was computed then it is used to scale the values.
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	    Same as NET_FLUX_APER_LO for the upper end of the credible interval.
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	    computed from the upper end of the credible interval (yes) or an observed NET_RATE (no).
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +      <DATA>The upper end of the credible interval of on the NET_PHOTFLUX_APER value obtained
change to "upper bound of the credible interval of the" and delete 'on'

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	  <DATA>The lower end of the credible interval of NET_MFLUX_APER</DATA>
change to "lower band of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	  <DATA>The upper end of the credible interval in the NET_MFLUX_APER</DATA>
change to "upper bound of the credible interval of the"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	  <DATA>Lower end of credible interval for unabsorbed model flux</DATA>
change to "lower bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +	  <DATA>Upper end of the credible interval for the unabsorbed model flux</DATA>
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Lower end of the credible interval of merged net rate computed using
change to "lower bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Same as previous for the upper end of the credible interval.</DATA>
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +    The aprates_photflux lower end of credible interval
change to "lower bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>    The aprates_photflux upper end of credible interval
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>The lower end of the credible inerval for the net photon flux computed by scaling
change to "lower  bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Same as above for the upper end of the credible interval.
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Same as above for the lower end of credible interval
change to "lower bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Same as above for the upper end of the credible interval.
change to "upper bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Same as above for the lower end of credible interval</DATA>
change to "lower bound of the credible interval"

2021-11-10 02:57 UTC, anetasie commented on share/doc/xml/srcflux.xml
> +<DATA>Same as above for the upper end of credible interval</DATA>
change to "upper bound of the credible interval"

2021-11-10 16:12 UTC, anetasie approved these changes
@hamogu Thanks for the update. It looks good.

2021-11-15 13:46 UTC, merged